name: Terraform & AWS ECR Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform
        

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="key_name=my-key" \
            -out=tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan
        working-directory: ./terraform

      - name: Export Terraform Output
        id: tf-output
        run: |
          echo "EC2_PUBLIC_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
          echo "EC2_PRIVATE_KEY=$(terraform output -raw private_key_pem)" >> $GITHUB_ENV
        working-directory: ./terraform

  docker:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: mcp-proj-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest


    ansible:
      name: Configure EC2 with Ansible
      runs-on: ubuntu-latest
      needs: docker
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup SSH key
          run: |
            echo "$EC2_PRIVATE_KEY" > private_key.pem
            chmod 400 private_key.pem

        - name: Install Ansible
          run: sudo apt-get update && sudo apt-get install -y ansible

        - name: Create Ansible inventory
          run: |
            echo "[app]" > inventory
            echo "${{ env.EC2_PUBLIC_IP }}" >> inventory

        - name: Run Ansible Playbook
          run: |
            ansible-playbook -i inventory playbook.yml --private-key private_key.pem -u ubuntu
