#!/usr/bin/env bash
set -a
source "../.env"
set +a

jq -n \
  --arg OPENAI_API_KEY "$OPENAI_API_KEY" \
  --arg SECRET_KEY "$SECRET_KEY" \
  --arg ALGORITHM "$ALGORITHM" \
  --arg ACCESS_TOKEN_EXPIRE_MINUTES "$ACCESS_TOKEN_EXPIRE_MINUTES" \
  --arg REFRESH_TOKEN_EXPIRE_DAYS "$REFRESH_TOKEN_EXPIRE_DAYS" \
  '{
    OPENAI_API_KEY: $OPENAI_API_KEY,
    SECRET_KEY: $SECRET_KEY,
    ALGORITHM: $ALGORITHM,
    ACCESS_TOKEN_EXPIRE_MINUTES: ($ACCESS_TOKEN_EXPIRE_MINUTES),
    REFRESH_TOKEN_EXPIRE_DAYS: ($REFRESH_TOKEN_EXPIRE_DAYS),
  }'
