#!/usr/bin/env bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -f "$DIR/../.env" ]; then
  set -a
  source "$DIR/../.env"
  set +a
fi

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
SECRET_KEY="${SECRET_KEY:-}"
ALGORITHM="${ALGORITHM:-HS256}"
ACCESS_TOKEN_EXPIRE_MINUTES="${ACCESS_TOKEN_EXPIRE_MINUTES:-30}"
REFRESH_TOKEN_EXPIRE_DAYS="${REFRESH_TOKEN_EXPIRE_DAYS:-7}"

jq -n \
  --arg OPENAI_API_KEY "$OPENAI_API_KEY" \
  --arg SECRET_KEY "$SECRET_KEY" \
  --arg ALGORITHM "$ALGORITHM" \
  --arg ACCESS_TOKEN_EXPIRE_MINUTES "$ACCESS_TOKEN_EXPIRE_MINUTES" \
  --arg REFRESH_TOKEN_EXPIRE_DAYS "$REFRESH_TOKEN_EXPIRE_DAYS" \
  '{
    OPENAI_API_KEY: $OPENAI_API_KEY,
    SECRET_KEY: $SECRET_KEY,
    ALGORITHM: $ALGORITHM,
    ACCESS_TOKEN_EXPIRE_MINUTES: ($ACCESS_TOKEN_EXPIRE_MINUTES),
    REFRESH_TOKEN_EXPIRE_DAYS: ($REFRESH_TOKEN_EXPIRE_DAYS),
  }'
